export const farmers = 
[
    {
        ID:1,
        firstname: 'kasun',
        lastname: 'pavithra',
        birthday: '1999-06-05',
        email: 'nid@gmail.com',
        nic_number: '992883241V',                 
        District: 'Colombo',
        Division: 'Moratuwa',
        Postal_Code: '13000',                    
        phone_number: '0765423123',
        crop:'Potato',
        address:'No12,kalgedihena road,gampaha',
        officer:'',
        approval:'Accepted'
    },
    {
        ID:2,
        firstname: 'Bimbi',
        lastname: 'Senarante',
        birthday: '1999-06-05',
        email: 'nid@gmail.com',
        nic_number: '992883241V',                 
        District: 'Colombo',
        Division: 'Kolonnawa',
        Postal_Code: '13000',                    
        phone_number: '0765423123',
        crop:'Potato',
        address:'No12,kalgedihena road,gampaha',
        officer:'',
        approval:'Declined'
    },
    {
        ID:3,
        firstname: 'Siththa',
        lastname: 'Senarante',
        birthday: '1999-06-05',
        email: 'nid@gmail.com',
        nic_number: '992883241V',                 
        District: 'Colombo',
        Division: 'Thimbirigasyaya',
        Postal_Code: '13000',                    
        phone_number: '0765423123',
        crop:'Potato',
        address:'No12,kalgedihena road,gampaha',
        officer:'',
        approval:'Idle'
    },
    {
        ID:4,
        firstname: 'Supula',
        lastname: 'Senarante',
        birthday: '1999-06-05',
        email: 'nid@gmail.com',
        nic_number: '992883241V',                 
        District: 'Colombo',
        Division: 'Ratmalana',
        Postal_Code: '13000',                    
        phone_number: '0765423123',
        crop:'Potato',
        address:'No12,kalgedihena road,gampaha',
        officer:'',
        approval:'Accepted'
    },
    {
        ID:5,
        firstname: 'jana',
        lastname: 'jothi',
        birthday: '1999-02-01',
        email: 'nsadasdd@gmail.com',
        nic_number: '992383241V',                 
        District: 'Colombo',
        Division: 'Ratmalana',
        Postal_Code: '13000',                    
        phone_number: '0765423123',
        crop:'Potato',
        address:'No12,kalgedihena road,gampaha',
        officer:'',
        approval:'Accepted'
    },
    
]
